import { type NextPage } from "next";
import React from "react";
import Head from "next/head";
import EditContactForm from "../components/forms/editContact";

const Edit: NextPage = () => {
  return (
    <>
      <Head>
        <title>Edit Contact Info</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <EditContactForm />
    </>
  );
};

export default Edit;
