import { type NextPage } from "next";
import React from "react";
import Head from "next/head";
import NewUserForm from "../components/forms/newUser";

const GetStarted: NextPage = () => {
  return (
    <>
      <Head>
        <title>Get Started</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <NewUserForm />
    </>
  );
};

export default GetStarted;
