import { type NextPage } from "next";
import React from "react";
import Head from "next/head";
import NewItemForm from "../components/forms/newItem";

const NewItem: NextPage = () => {
  return (
    <>
      <Head>
        <title>Get Started</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <NewItemForm />
    </>
  );
};

export default NewItem;