import { type NextPage } from "next";
import React from "react";
import Head from "next/head";
import UpdateItemForm from "@qrfound/components/forms/updateItem";

const UpdateItem: NextPage = () => {
  return (
    <>
      <Head>
        <title>Get Started</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <UpdateItemForm />
    </>
  );
};

export default UpdateItem;
